name: Build React app and deploy to GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: build
    runs-on: ubuntu-26.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
